name: Docker Image Build+Push

on:
  push:
    branches: [ "master" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: docker-publish
      uses: bitovi/github-actions-docker-publish@v1
      with:
        docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
        docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}

     
