name: Docker minimized build+push Manual

on: workflow_dispatch

jobs:

  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}   
    
    - id: build-tag-push
      shell: bash
      run: |
        #Custom:
        ORG_NAME="basleijenhorst"
        IMAGE_TAG="latest"
        DOCKERFILE_NAME="Dockerfile_minimal"
        #
        #Predefined:
        REPO_NAME=$(echo $GITHUB_REPOSITORY | sed 's/^.*\///')
        IMAGE_NAME="$ORG_NAME/$REPO_NAME"
        #
        echo "::group::Build Image"
        echo "Building $IMAGE_NAME"
        docker build --file $DOCKERFILE_NAME --pull -t $IMAGE_NAME:$IMAGE_TAG .
        echo "::endgroup::"
        echo "::group::Push Image"
        echo "Pushing docker image $IMAGE_NAME:$IMAGE_TAG"
        docker push $IMAGE_NAME:$IMAGE_TAG
        echo "::endgroup::"
        echo "tag=$IMAGE_TAG"  >> $GITHUB_ENV
        echo "image=$IMAGE_NAME" >> $GITHUB_ENV
        echo 'Complete!'

